# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: armajchr <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/02 12:11:06 by armajchr          #+#    #+#              #
#    Updated: 2019/04/03 14:39:02 by armajchr         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ft_display_file.c \
	  function.c

all: $(NAME)

$(NAME): 
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:

fclean: clean
	rm -rf $(NAME)
